version: '2'
services:
  reverse:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secret
